from django.core.exceptions import ValidationError


def validate_document_count(cls, business_trips_request):   # Переделать валидатор
    pass
